name: 'CI/CD Workflow'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [ developer ]
    uses: ./.github/workflows/pipeline.yml
    with:
      environment: ${{ matrix.target }}
