name: 'CI/CD Workflow'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  development_pipeline:
    - uses: ./.github/workflows/pipeline.yml
      with:
        environment: development
    - name: Checkout
      uses: actions/checkout@v4

