name: 'CI/CD Workflow'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  development_pipeline:
    name: Run Development Pipeline
    runs-on: ubuntu-latest
    uses: ./.github/workflows/pipeline.yml
    with:
      environment: development
