name: 'Publish Lambda to AWS'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  test-lambda:
    name: 'Test Lambda'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: 'sbt'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Build and Test with Coverage
        run: |
          sbt coverage test
          sbt coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish-lambda:
    name: 'Publish Lambda'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    needs: test-lambda
    env:
      TF_VAR_LAMBDA_BUCKET: "${{ vars.TF_VAR_RECIPIENT }}-${{ vars.TF_VAR_DISCORD_NAME }}-lambda-functions"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: 'sbt'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Assemble New Lambda Function
        id: assemble-lambda-function
        run: |
          ASSEMBLY_PATH=$(sbt assembly | grep -e "Assembly jar up to date: " -e "Built: " | awk -F' ' '{print $NF}' | awk -F".jar" '{printf "%s.jar", $1}')
          echo "ASSEMBLY_PATH=$ASSEMBLY_PATH" >> $GITHUB_OUTPUT
          echo ${{ env.TF_VAR_LAMBDA_BUCKET }} > variables.txt
          basename $ASSEMBLY_PATH >> variables.txt

      - name: Upload Variable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: variables
          path: variables.txt

      - name: Upload Assembled
        uses: actions/upload-artifact@v4
        with:
          name: lambdaFunction
          path: ${{ steps.assemble-lambda-function.outputs.ASSEMBLY_PATH }}


  publish-lambda-to-aws:
    name: "Publish to AWS"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    needs: publish-lambda
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TF_AWS_VAR_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download Variable Artifact
        uses: actions/download-artifact@v4
        with:
          name: variables
          path: variables.txt

      - name: Download Assembled
        uses: actions/upload-artifact@v4
        with:
          name: lambdaFunction
          path: DiscordEmailWebhook.jar

      - name: Create (if exists) S3 bucket
        with:
          aws_bucket: "$(head -1 variable.txt)"
        run: aws s3 mb "s3://$aws_bucket"

      - name: Copy Program to S3 Bucket
        with:
          aws_bucket: "$(head -1 variable.txt)"
        run: aws s3 cp DiscordEmailWebhook.jar "s3://$aws_bucket"
