name: 'Run Pipeline'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  terraform:
    name: Deploy Terraform
    # needs: lambda

    strategy:
      matrix:
        target: [ development ]

    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
