name: 'Run Pipeline'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write

jobs:
  lambda:
    name: Deploy Lambda

    strategy:
      matrix:
        target: [ developer ]

    uses: ./.github/workflows/lambda.yml
    with:
      environment: ${{ matrix.target }}

  terraform:
    name: Deploy Terraform
    needs: lambda

    strategy:
      matrix:
        target: [ developer ]

    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.target }}
