name: 'Run Pipeline'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  pipeline:
    name: Deploy Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ developer ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Lambda
        uses: ./.github/workflows/lambda
        with:
          environment: ${{ matrix.target }}

      - name: Set Filename Global Variable
        uses: actions/download-artifact@v4
        with:
          name: variables
          path: variables.txt

      - name: Deploy Services with Terraform
        uses: ./.github/workflows/terraform
        with:
          environment: ${{ matrix.target }}
          bucket: "$(head -1 variables.txt)"
          key: "$(tail -1 variables.txt)"
