name: 'Run Pipeline'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  lambda:
    strategy:
      matrix:
        target: [ developer ]
    uses: ./.github/workflows/lambda.yml
    with:
      environment: ${{ matrix.target }}

  terraform:
    needs: lambda
    strategy:
      matrix:
        target: [ developer ]
    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.target }}
