name: 'Run Pipeline'

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ developer ]

    uses: ./.github/workflows/lambda.yml
    with:
      environment: ${{ matrix.target }}

  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    needs: lambda

    strategy:
      matrix:
        target: [ developer ]

    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.target }}
