name: 'Deploy Services with Terraform'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_discord_name: ${{ vars.TF_VAR_DISCORD_NAME }}
  TF_VAR_domain_name: ${{ vars.TF_VAR_DOMAIN_NAME }}
  TF_VAR_recipient: ${{ vars.TF_VAR_RECIPIENT }}
  TF_VAR_webhook_address: ${{ vars.TF_VAR_WEBHOOK_ADDRESS }}
  TF_VAR_lambda_bucket: ""
  TF_VAR_lambda_key: ""
  TF_VAR_aws_access_key_id: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.TF_AWS_VAR_SECRET_ACCESS_KEY }}
  TF_VAR_region: ${{ vars.AWS_REGION }}

jobs:
  check-terraform:
    name: 'Check Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

  plan-terraform:
    name: 'Plan Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    needs: check-terraform

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Filename Global Variable
      uses: actions/download-artifact@v4
      with:
        name: variables

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

  publish-terraform:
    name: 'Publish Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    needs: plan-terraform

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Set Filename Global Variable
        uses: actions/download-artifact@v4
        with:
          name: variables
          path: variables.txt

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_lambda_bucket: "$(head -1 variables.txt)"
          TF_VAR_lambda_key: "$(tail -1 variables.txt)"
        run: terraform apply -auto-approve
